import { Palette } from '@/constants/Palette';
import { StyleSheet } from 'react-native';

const {
  backgroundAlt: BACKGROUND,
  surface: SURFACE,
  surfaceSubtle: SURFACE_SUBTLE,
  borderAlt: BORDER,
  textPrimary: TEXT_PRIMARY,
  textMuted: TEXT_MUTED,
  primary: PRIMARY,
  successStrong: SUCCESS,
  warning: WARNING,
} = Palette;

export const calendarStyles = StyleSheet.create({
  calendarGrid: {
    backgroundColor: BACKGROUND,
    borderRadius: 16,
    flex: 1,
    marginTop: 8,
  },
  container: {
    flex: 1,
    paddingBottom: 8,
    paddingHorizontal: 8,
    paddingTop: 12,
  },
  dayCell: {
    flex: 1,
    marginHorizontal: 1,
    marginVertical: 1,
  },
  dayEventList: {
    gap: 1,
    marginTop: 1,
  },
  dayHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
    justifyContent: 'center',
  },
  dayInner: {
    backgroundColor: SURFACE,
    borderColor: 'rgba(148, 163, 184, 0.35)',
    borderRadius: 10,
    borderWidth: StyleSheet.hairlineWidth,
    flex: 1,
    justifyContent: 'flex-start',
    overflow: 'hidden',
    paddingBottom: 3,
    paddingHorizontal: 4,
    paddingTop: 2,
  },
  dayInnerSelected: {
    backgroundColor: SURFACE,
    borderColor: BORDER,
    borderWidth: 2,
  },
  dayInnerToday: {
    backgroundColor: 'rgba(37, 99, 235, 0.04)',
  },
  dayModalCompany: {
    color: TEXT_MUTED,
    fontSize: 12,
  },
  dayModalInfo: {
    flex: 1,
    gap: 2,
  },
  dayModalItem: {
    alignItems: 'center',
    backgroundColor: SURFACE_SUBTLE,
    borderColor: BORDER,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 8,
  },
  dayModalList: {
    gap: 10,
    maxHeight: 260,
    paddingBottom: 4,
  },
  dayModalMeta: {
    alignItems: 'center',
    flex: 1,
    flexDirection: 'row',
    gap: 8,
  },
  dayModalTime: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 4,
  },
  dayModalTimeText: {
    color: TEXT_MUTED,
    fontSize: 12,
  },
  dayModalTitle: {
    color: TEXT_PRIMARY,
    fontSize: 14,
    fontWeight: '600',
  },
  dayNumber: {
    color: TEXT_PRIMARY,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 20,
  },
  daySummaryMore: {
    color: TEXT_MUTED,
    fontSize: 9,
    marginLeft: 2,
  },
  daySummaryRow: {
    alignItems: 'center',
    borderRadius: 8,
    flexDirection: 'row',
    gap: 3,
    marginTop: 1,
    minHeight: 14,
    paddingHorizontal: 4,
    paddingVertical: 1,
  },
  daySummaryRowCandidate: {
    backgroundColor: 'rgba(245, 158, 11, 0.08)',
  },
  daySummaryRowConfirmed: {
    backgroundColor: 'rgba(22, 163, 74, 0.08)',
  },
  daySummaryText: {
    flex: 1,
    fontSize: 9,
  },
  daySummaryTextCandidate: {
    color: WARNING,
    fontWeight: '600',
  },
  daySummaryTextConfirmed: {
    color: SUCCESS,
    fontWeight: '600',
  },
  emptyDayMessage: {
    color: TEXT_MUTED,
    paddingVertical: 12,
    textAlign: 'center',
  },
  modalCaption: {
    color: TEXT_MUTED,
    fontSize: 12,
    marginBottom: 8,
    marginTop: 4,
  },
  modalCard: {
    backgroundColor: SURFACE,
    borderColor: BORDER,
    borderRadius: 24,
    borderWidth: StyleSheet.hairlineWidth,
    elevation: 8,
    gap: 16,
    padding: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 24,
  },
  modalLabel: {
    color: TEXT_MUTED,
    fontSize: 12,
  },
  modalOverlay: {
    alignItems: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    flex: 1,
    justifyContent: 'center',
    padding: 24,
  },
  modalSection: {
    gap: 4,
    marginTop: 4,
  },
  modalShell: {
    maxWidth: 420,
    width: '100%',
  },
  modalSubtitle: {
    color: TEXT_MUTED,
    fontSize: 13,
  },
  modalTitle: {
    color: TEXT_PRIMARY,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'left',
  },
  modalValue: {
    color: TEXT_PRIMARY,
    fontSize: 14,
    fontWeight: '600',
  },
  monthButton: {
    alignItems: 'center',
    backgroundColor: SURFACE,
    borderColor: BORDER,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    height: 40,
    justifyContent: 'center',
    width: 40,
  },
  monthLabel: {
    color: TEXT_PRIMARY,
    fontSize: 18,
    fontWeight: '700',
  },
  monthSwitcher: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
  },
  outsideCell: {
    opacity: 0.55,
  },
  outsideDayNumber: {
    color: TEXT_MUTED,
  },
  primaryButton: {
    alignItems: 'center',
    backgroundColor: PRIMARY,
    borderRadius: 999,
    flexDirection: 'row',
    gap: 8,
    justifyContent: 'center',
    marginTop: 8,
    paddingVertical: 12,
  },
  primaryButtonLabel: {
    color: '#FFFFFF',
    fontWeight: '700',
  },
  safeArea: {
    backgroundColor: BACKGROUND,
    flex: 1,
  },
  screen: {
    backgroundColor: BACKGROUND,
    flex: 1,
  },
  statusTag: {
    alignItems: 'center',
    borderRadius: 999,
    flexDirection: 'row',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  statusTagLabel: {
    fontSize: 11,
    fontWeight: '600',
  },
  todayDayNumber: {
    color: PRIMARY,
  },
  todayPill: {
    alignItems: 'center',
    backgroundColor: 'rgba(37, 99, 235, 0.10)',
    borderRadius: 9,
    height: 20,
    justifyContent: 'center',
    paddingHorizontal: 8,
  },
  todayPillText: {
    color: PRIMARY,
    fontSize: 12,
    fontWeight: '700',
    lineHeight: 20,
  },
  weekDay: {
    color: TEXT_MUTED,
    flex: 1,
    fontSize: 12,
    fontWeight: '600',
    textAlign: 'center',
  },
  weekHeader: {
    flexDirection: 'row',
    marginBottom: 0,
    paddingHorizontal: 0,
  },
  weekRow: {
    flex: 1,
    flexDirection: 'row',
  },
});
