import { StyleSheet } from "react-native";

import { Palette } from "@/constants/Palette";
import { NOTO_SANS_JP } from "@/constants/Typography";

const {
  background: BACKGROUND,
  surface: SURFACE,
  surfaceSubtle: SURFACE_SUBTLE,
  border: BORDER,
  textPrimary: TEXT_PRIMARY,
  textMuted: TEXT_MUTED,
  primary: PRIMARY,
  success: SUCCESS,
  danger: DANGER,
} = Palette;

export const companiesStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: BACKGROUND,
  },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  pageHeader: {
    marginHorizontal: -20,
    paddingLeft: 20,
    paddingRight: 0,
    paddingBottom: 12,
    paddingTop: 0,
    marginBottom: 28,
  },
  list: { flex: 1 },
  listContent: { gap: 16, paddingBottom: 160 },
  pageHeaderTitle: {
    color: TEXT_PRIMARY,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "700",
  },
  pageHeaderSubtitle: {
    color: TEXT_MUTED,
  },
  primaryButton: {
    marginTop: 0,
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    backgroundColor: PRIMARY,
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 18,
    alignSelf: "flex-end",
    flexShrink: 0,
  },
  primaryButtonLabel: { color: "#FFFFFF", fontWeight: "700" },
  emptyList: {
    marginHorizontal: 0,
    padding: 24,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    backgroundColor: SURFACE,
    alignItems: "center",
    gap: 8,
  },
  emptyTitle: { color: TEXT_PRIMARY, fontWeight: "600", fontSize: 16 },
  emptyCopy: { color: TEXT_MUTED, fontSize: 13, textAlign: "center" },
  formCard: {
    backgroundColor: SURFACE,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    padding: 20,
    gap: 24,
  },
  formHeader: {
    gap: 6,
  },
  sectionGroup: {
    gap: 4,
  },
  formTitle: {
    color: TEXT_PRIMARY,
    fontSize: 18,
    fontWeight: "700",
  },
  formHeading: {
    color: TEXT_PRIMARY,
    fontWeight: "700",
    fontSize: 16,
    letterSpacing: 0.2,
  },
  formSection: {
    gap: 14,
    padding: 16,
    borderRadius: 16,
    backgroundColor: SURFACE_SUBTLE,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
  },
  scheduleSection: {
    gap: 14,
  },
  taskSection: {
    gap: 14,
  },
  taskInlineSection: {
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: BORDER,
    gap: 14,
  },
  inputBlock: {
    width: "100%",
    gap: 6,
  },
  fieldLabel: {
    color: TEXT_PRIMARY,
    fontWeight: "600",
    fontSize: 16,
    letterSpacing: 0.2,
  },
  labelRow: { flexDirection: "row", alignItems: "center", gap: 6 },
  requiredTag: {
    color: DANGER,
    fontSize: 12,
    fontWeight: "600",
  },
  card: {
    borderRadius: 24,
    shadowColor: "#CBD5F5",
    shadowOpacity: 0.25,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 24,
    elevation: 4,
  },
  cardPressed: {
    transform: [{ scale: 0.99 }],
    opacity: 0.9,
  },
  cardSurface: {
    borderRadius: 24,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: "rgba(148, 163, 184, 0.24)",
    padding: 20,
    gap: 16,
    overflow: "hidden",
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    gap: 12,
  },
  companyName: {
    flexShrink: 1,
    color: TEXT_PRIMARY,
    fontSize: 16,
    fontWeight: "700",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(37, 99, 235, 0.12)",
  },
  statusBadgeLabel: { color: PRIMARY, fontWeight: "700", fontSize: 13 },
  cardMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
  },
  metaColumn: {
    flex: 1,
    gap: 4,
  },
  metaLabel: {
    color: TEXT_MUTED,
    fontSize: 11,
    fontWeight: "600",
    letterSpacing: 0.4,
  },
  metaValue: {
    color: TEXT_PRIMARY,
    fontWeight: "600",
    fontSize: 14,
  },
  metaAction: {
    color: TEXT_PRIMARY,
    fontSize: 12,
    lineHeight: 16,
  },
  metaPills: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    justifyContent: "flex-end",
  },
  metaPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(37, 99, 235, 0.1)",
  },
  metaPillConfirmed: {
    backgroundColor: "rgba(34, 197, 94, 0.12)",
  },
  metaPillLabel: {
    fontSize: 11,
    fontWeight: "600",
  },
  metaConfirmedLabel: {
    color: SUCCESS,
  },
  metaCandidateLabel: {
    color: PRIMARY,
  },
  cardCandidateRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 8,
    backgroundColor: "rgba(37, 99, 235, 0.08)",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  cardCandidateLabel: {
    color: PRIMARY,
    fontWeight: "600",
    fontSize: 11,
  },
  noteSnippet: {
    color: TEXT_MUTED,
    fontSize: 11,
    lineHeight: 16,
    marginTop: 12,
  },
  input: {
    borderWidth: 1.5,
    borderColor: "rgba(37, 99, 235, 0.35)",
    borderRadius: 14,
    paddingHorizontal: 16,
    paddingVertical: 4,
    fontSize: 14,
    fontFamily: NOTO_SANS_JP.semibold,
    backgroundColor: "#F1F5FF",
    color: TEXT_PRIMARY,
  },
  selectInput: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    minHeight: 52,
  },
  selectContent: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  selectIcon: {
    width: 44,
    height: 44,
    borderRadius: 16,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
  },
  selectTexts: {
    flex: 1,
  },
  selectValue: {
    color: TEXT_PRIMARY,
    fontWeight: "700",
  },
  selectDescription: {
    color: TEXT_MUTED,
    fontSize: 12,
  },
  selectPlaceholder: {
    color: TEXT_MUTED,
    fontWeight: "600",
  },
  multilineInput: { minHeight: 96, textAlignVertical: "top" },
  secondaryButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: SURFACE_SUBTLE,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
  },
  secondaryButtonDisabled: {
    opacity: 0.5,
  },
  secondaryButtonLabel: { color: PRIMARY, fontWeight: "600" },
  scheduleActions: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "flex-end",
    alignItems: "center",
    alignSelf: "flex-end",
    gap: 10,
  },
  scheduleSummaryCard: {
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    backgroundColor: SURFACE,
    padding: 16,
    gap: 16,
  },
  scheduleSummaryDivider: {
    paddingTop: 16,
    marginTop: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: BORDER,
  },
  taskComposer: {
    width: "100%",
  },
  taskActionsRow: {
    marginTop: 8,
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "center",
    justifyContent: "flex-end",
    gap: 12,
  },
  taskInput: {
    flex: 1,
  },
  taskDueButton: {
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  taskAddButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  taskDuePreview: {
    marginTop: 8,
    width: "100%",
    gap: 8,
  },
  taskDueClearButton: {
    alignSelf: "flex-end",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  taskDueClearLabel: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: "600",
  },
  taskListPreview: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  taskPill: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: SURFACE_SUBTLE,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
  },
  taskPillLabel: {
    color: TEXT_PRIMARY,
    fontWeight: "600",
  },
  taskPillText: {
    flexDirection: "column",
    gap: 2,
    alignItems: "flex-start",
  },
  taskPillDue: {
    color: PRIMARY,
    fontSize: 11,
  },
  taskPillRemove: {
    padding: 2,
  },
  confirmedBlock: {
    gap: 8,
  },
  candidateBlock: {
    gap: 8,
  },
  formLabel: {
    color: TEXT_PRIMARY,
    fontWeight: "600",
  },
  formCaption: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: "600",
    letterSpacing: 0.4,
  },
  formHint: {
    color: TEXT_MUTED,
    fontSize: 12,
  },
  modalActions: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 16,
    marginTop: 16,
    paddingHorizontal: 20,
  },
  createModalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.55)",
    padding: 20,
    justifyContent: "center",
  },
  createModalCard: {
    backgroundColor: SURFACE,
    borderRadius: 24,
    paddingVertical: 20,
    paddingHorizontal: 0,
    maxHeight: "90%",
  },
  createModalContent: {
    paddingHorizontal: 20,
    gap: 24,
  },
  modalButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    backgroundColor: SURFACE_SUBTLE,
  },
  modalButtonLabel: { color: TEXT_PRIMARY, fontWeight: "600" },
  modalPrimaryButton: { backgroundColor: PRIMARY, borderColor: PRIMARY },
  modalPrimaryLabel: { color: "#FFFFFF", fontWeight: "700" },
  chipColumn: { gap: 12 },
  scheduleTitleInput: {
    paddingVertical: 8,
  },
});
