import { StyleSheet } from "react-native";

import { Palette } from "@/constants/Palette";

const {
  background: BACKGROUND,
  surface: SURFACE,
  surfaceSubtle: SURFACE_SUBTLE,
  border: BORDER,
  textPrimary: TEXT_PRIMARY,
  textMuted: TEXT_MUTED,
  primary: PRIMARY,
} = Palette;

export const homeStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: BACKGROUND },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 30,
  },
  appHero: {
    marginBottom: 24,
    paddingVertical: 0,
  },
  appHeroIcon: {
    width: 48,
    height: 48,
  },
  pageHeaderTitle: {
    color: TEXT_PRIMARY,
    fontSize: 28,
    lineHeight: 30,
    fontWeight: "700",
  },
  summarySection: {
    marginBottom: 24,
    padding: 16,
    borderRadius: 20,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    backgroundColor: SURFACE_SUBTLE,
    gap: 16,
    shadowColor: "#000",
    shadowOpacity: 0.03,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 3 },
    elevation: 2,
  },
  summaryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  summaryTitle: { color: TEXT_PRIMARY, fontWeight: "700", fontSize: 16 },
  summarySubtitle: { color: TEXT_MUTED, fontSize: 12, fontWeight: "600" },
  summaryBadge: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: "rgba(37, 99, 235, 0.12)",
  },
  summaryBadgeLabel: { color: PRIMARY, fontWeight: "700", fontSize: 12 },
  summaryScroll: { paddingRight: 8 },
  statusCard: {
    width: 180,
    borderRadius: 18,
    borderWidth: StyleSheet.hairlineWidth,
    backgroundColor: SURFACE,
    padding: 12,
    marginRight: 12,
    gap: 8,
  },
  statusCardLast: { marginRight: 0 },
  statusCardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  statusIcon: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: StyleSheet.hairlineWidth,
  },
  statusCardTexts: { flex: 1 },
  statusCardLabel: { color: TEXT_PRIMARY, fontWeight: "700", fontSize: 13 },
  statusCardCaption: { color: TEXT_MUTED, fontSize: 11, lineHeight: 14 },
  statusCardCountRow: {
    flexDirection: "row",
    alignItems: "baseline",
    gap: 4,
  },
  statusCardCount: { color: TEXT_PRIMARY, fontSize: 26, fontWeight: "700" },
  statusCardCountUnit: { color: TEXT_MUTED, fontWeight: "600" },
  list: { flex: 1 },
  listContent: { gap: 12, paddingBottom: 120 },
  listEmptyContent: { flexGrow: 1, justifyContent: "center" },
  empty: {
    backgroundColor: SURFACE_SUBTLE,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    padding: 24,
    alignItems: "center",
    gap: 6,
  },
  emptyText: { color: TEXT_PRIMARY, fontWeight: "600" },
  emptyButtonStack: {
    marginTop: 24,
    flexDirection: "column",
    gap: 14,
    alignItems: "center",
  },
  emptyButton: {
    alignSelf: "center",
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
    backgroundColor: PRIMARY,
  },
  emptyButtonLabel: { color: "#FFFFFF", fontWeight: "700" },
  taskRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: SURFACE,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  check: { width: 28, alignItems: "center" },
  checkDone: {},
  taskBody: { flex: 1, gap: 4 },
  taskTitle: { color: TEXT_PRIMARY, fontWeight: "600" },
  done: { opacity: 0.5, textDecorationLine: "line-through" },
  companyLink: {
    color: PRIMARY,
    fontSize: 12,
    fontWeight: "600",
    maxWidth: "40%",
  },
  due: { color: TEXT_MUTED, fontSize: 11 },
  deleteBtn: { padding: 4 },
  tasksHeader: {
    marginTop: 8,
    marginBottom: 12,
    flexDirection: "row",
    alignItems: "baseline",
    justifyContent: "space-between",
  },
  tasksTitle: {
    color: TEXT_PRIMARY,
    fontSize: 16,
    fontWeight: "700",
  },
  tasksSubtitle: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontWeight: "600",
  },
  scheduleRow: { alignItems: "center", borderColor: "rgba(37, 99, 235, 0.25)" },
  scheduleIconBadge: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(37, 99, 235, 0.12)",
  },
  scheduleTitle: { color: TEXT_PRIMARY, fontSize: 13, fontWeight: "600" },
  scheduleLabel: { color: TEXT_MUTED, fontSize: 12, fontWeight: "600" },
  scheduleLink: { padding: 4 },
  scheduleMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
});
