import { StyleSheet } from "react-native";

import { Palette } from "@/constants/Palette";

const {
  background: BACKGROUND,
  surface: SURFACE,
  border: BORDER,
  textPrimary: TEXT_PRIMARY,
  textMuted: TEXT_MUTED,
  primary: PRIMARY,
} = Palette;

export const tasksStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: BACKGROUND },
  container: {
    flex: 1,
    paddingHorizontal: 20,
    paddingTop: 24,
  },
  pageHeader: { marginBottom: 12, paddingVertical: 0 },
  pageHeaderTitle: {
    color: TEXT_PRIMARY,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: "700",
  },
  pageHeaderSubtitle: { color: TEXT_MUTED, fontSize: 13 },
  list: { flex: 1 },
  listContent: { gap: 12, paddingBottom: 120 },
  sectionHeader: { gap: 2, marginBottom: 8 },
  sectionTitle: { color: TEXT_PRIMARY, fontSize: 16, fontWeight: "700" },
  sectionCaption: { color: TEXT_MUTED, fontSize: 12 },
  sectionSeparator: { height: 16 },
  emptyContent: { flexGrow: 1, justifyContent: "center" },
  empty: {
    backgroundColor: SURFACE,
    borderRadius: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    padding: 20,
    alignItems: "center",
    gap: 6,
  },
  emptyText: { color: TEXT_PRIMARY, fontWeight: "600" },
  emptyHint: { color: TEXT_MUTED, fontSize: 12, textAlign: "center" },
  taskRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    backgroundColor: SURFACE,
    borderRadius: 14,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  check: { width: 28, alignItems: "center" },
  checkDone: { opacity: 0.5 },
  taskBody: { flex: 1, gap: 4 },
  taskTitle: { color: TEXT_PRIMARY, fontWeight: "600" },
  done: { opacity: 0.5, textDecorationLine: "line-through" },
  metaRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 10,
  },
  companyLink: {
    color: PRIMARY,
    fontSize: 12,
    fontWeight: "600",
    maxWidth: "45%",
  },
  due: { color: TEXT_MUTED, fontSize: 12 },
  dueMuted: { color: TEXT_MUTED, fontSize: 12, fontStyle: "italic" },
  rowActions: { flexDirection: "row", alignItems: "center", gap: 4 },
  iconButton: { padding: 4 },
  deleteBtn: { padding: 4 },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(15, 23, 42, 0.5)",
    padding: 24,
    justifyContent: "center",
  },
  modalCard: {
    backgroundColor: SURFACE,
    borderRadius: 20,
    padding: 20,
    gap: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
  },
  modalTitle: {
    color: TEXT_PRIMARY,
    fontSize: 18,
    fontWeight: "700",
    textAlign: "center",
  },
  modalField: { gap: 8 },
  modalLabel: { color: TEXT_PRIMARY, fontWeight: "600", fontSize: 13 },
  modalInput: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: TEXT_PRIMARY,
  },
  modalFieldHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  clearDueButton: { color: PRIMARY, fontWeight: "600" },
  modalDueRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  modalDueValue: {
    color: TEXT_PRIMARY,
    fontWeight: "600",
    flex: 1,
    marginRight: 12,
  },
  duePickerButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: "rgba(37, 99, 235, 0.12)",
  },
  duePickerLabel: { color: PRIMARY, fontWeight: "600", fontSize: 12 },
  modalActions: { flexDirection: "row", justifyContent: "flex-end", gap: 10 },
  modalButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
  },
  modalSecondary: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    backgroundColor: "transparent",
  },
  modalPrimary: {
    backgroundColor: PRIMARY,
  },
  modalSecondaryLabel: { color: TEXT_MUTED, fontWeight: "600" },
  modalPrimaryLabel: { color: "#FFFFFF", fontWeight: "700" },
});
