import { StyleSheet } from 'react-native';

import { Palette } from '@/constants/Palette';
import { NOTO_SANS_JP } from '@/constants/Typography';

const {
  background: BACKGROUND,
  surface: SURFACE,
  border: BORDER,
  textPrimary: TEXT_PRIMARY,
  textMuted: TEXT_MUTED,
  primary: PRIMARY,
} = Palette;

export const tasksStyles = StyleSheet.create({
  clearDueButton: { color: PRIMARY, fontWeight: '600', fontFamily: NOTO_SANS_JP.semibold },
  container: {
    flex: 1,
    paddingHorizontal: 16,
    paddingTop: 20,
  },
  duePickerButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(37, 99, 235, 0.12)',
  },
  duePickerLabel: {
    color: PRIMARY,
    fontWeight: '600',
    fontSize: 12,
    fontFamily: NOTO_SANS_JP.semibold,
  },
  emptyContent: { flexGrow: 1, justifyContent: 'center' },
  emptyList: {
    marginHorizontal: 0,
    paddingVertical: 24,
    alignItems: 'center',
    gap: 8,
    backgroundColor: BACKGROUND,
  },
  emptyTitle: {
    color: TEXT_PRIMARY,
    fontWeight: '600',
    fontSize: 16,
    fontFamily: NOTO_SANS_JP.semibold,
  },
  list: { flex: 1 },
  listContent: {
    gap: 16,
    paddingBottom: 80,
  },
  modalActions: { flexDirection: 'row', justifyContent: 'flex-end', gap: 10 },
  modalButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 18,
    paddingVertical: 10,
    borderRadius: 999,
  },
  modalCard: {
    backgroundColor: SURFACE,
    borderRadius: 20,
    padding: 20,
    gap: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
  },
  modalDueRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  modalDueValue: {
    color: TEXT_PRIMARY,
    fontWeight: '600',
    flex: 1,
    marginRight: 12,
    fontFamily: NOTO_SANS_JP.semibold,
  },
  modalField: { gap: 8 },
  modalFieldHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalInput: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    color: TEXT_PRIMARY,
    fontFamily: NOTO_SANS_JP.medium,
  },
  modalLabel: {
    color: TEXT_PRIMARY,
    fontWeight: '600',
    fontSize: 13,
    fontFamily: NOTO_SANS_JP.semibold,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.5)',
    padding: 24,
    justifyContent: 'center',
  },
  modalPrimary: {
    backgroundColor: PRIMARY,
  },
  modalPrimaryLabel: { color: '#FFFFFF', fontWeight: '700', fontFamily: NOTO_SANS_JP.bold },
  modalSecondary: {
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: BORDER,
    backgroundColor: 'transparent',
  },
  modalSecondaryLabel: {
    color: TEXT_MUTED,
    fontWeight: '600',
    fontFamily: NOTO_SANS_JP.semibold,
  },
  modalTitle: {
    color: TEXT_PRIMARY,
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    fontFamily: NOTO_SANS_JP.bold,
  },
  pageHeader: { marginBottom: 12, paddingVertical: 0 },
  pageHeaderSubtitle: {
    color: TEXT_MUTED,
    fontSize: 13,
    fontFamily: NOTO_SANS_JP.medium,
  },
  pageHeaderTitle: {
    color: TEXT_PRIMARY,
    fontSize: 24,
    lineHeight: 30,
    fontWeight: '700',
    fontFamily: NOTO_SANS_JP.bold,
  },
  safeArea: { flex: 1, backgroundColor: BACKGROUND },
  sectionCaption: {
    color: TEXT_MUTED,
    fontSize: 12,
    fontFamily: NOTO_SANS_JP.medium,
  },
  sectionHeader: { gap: 2, marginBottom: 8 },
  sectionSeparator: {
    height: 12,
  },
  sectionTitle: {
    color: TEXT_PRIMARY,
    fontSize: 16,
    fontWeight: '700',
    fontFamily: NOTO_SANS_JP.bold,
  },
  taskRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: SURFACE,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.4)',
    paddingHorizontal: 14,
    paddingVertical: 7,
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 2 },
    elevation: 1,
  },
  taskContent: {
    flex: 1,
    flexDirection: 'column',
  },
  taskMain: {
    flexShrink: 1,
    alignItems: 'flex-start',
    gap: 0,
  },
  taskTitle: {
    fontSize: 16,
    fontWeight: '500',
    color: TEXT_PRIMARY,
    fontFamily: NOTO_SANS_JP.semibold,
    transform: [{ translateY: 4 }],
  },
});
